name: Build and Publish Docker Image

on:
  push:
    branches:
      - main


jobs:
  build-and-publish:
    runs-on: ubuntu22

    env:
      IMAGE_NAME: rbehzadan/prose-chunker
      IMAGE_TAG: {CI_COMMIT_TAG}-${CI_PIPELINE_ID}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${DOCKER_HUB_USERNAME}
          password: ${DOCKER_HUB_PASSWORD}

      - name: Push Docker image to Docker Hub
        run: docker push ${IMAGE_NAME}:${IMAGE_TAG}
